version: '3.8'

services:
  web:
    build: .
    container_name: django-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
