# Generated by Django 5.1.5 on 2025-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('target_muscle', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Legs', 'Legs'), ('Core', 'Core')], max_length=10)),
                ('equipment_required', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty_level', models.CharField(choices=[('Beg', 'Beginner'), ('Int', 'Intermediate'), ('Adv', 'Advanced')], max_length=3)),
                ('category', models.CharField(max_length=50)),
                ('exercise_type', models.CharField(choices=[('ST', 'Strength Training'), ('CA', 'Cardio'), ('FL', 'Flexibility'), ('BA', 'Balance')], max_length=2)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('has_duration', models.BooleanField()),
            ],
        ),
    ]
